// Writers — the side-effecting half of `schema-gen`.
//
// Three artefacts go to disk per run:
//   1. One `.d.ts` per domain under `<outDir>/`, containing only the
//      resolved type aliases — no Zod imports, no runtime values.
//   2. `<outDir>/schema-map.json`, mapping each domain slug to the
//      list of types it contains. Programmatic consumers (e.g. an
//      AI agent that wants to fetch one domain at a time) read this
//      first to decide which `.d.ts` to load.
//   3. `<appRoot>/AI_MANIFEST.md`, a human + AI-readable routing
//      table. Lives at the app root so a coding agent's standard
//      "look in the project root" heuristic finds it.

import { join, posix, relative, sep } from 'node:path';
import fse from 'fs-extra';
import type { ExtractedDomain } from './extractor.js';
import { info } from './log.js';

export interface WriteOutputArgs {
  domains: ExtractedDomain[];
  /** Absolute path to the directory receiving per-domain `.d.ts`
   *  files and `schema-map.json`. */
  outDir: string;
  /** Absolute path to the consuming app's root directory.
   *  `AI_MANIFEST.md` is written here. */
  appRoot: string;
}

const HEADER_PREFIX = '// Auto-generated by @unsupervised/schemas / schema-gen — DO NOT EDIT.';

/** Wipe and rewrite the output. Called from the CLI; pure I/O. */
export async function writeOutput(args: WriteOutputArgs): Promise<void> {
  await fse.emptyDir(args.outDir);

  // ── Per-domain .d.ts files ────────────────────────────────────
  for (const domain of args.domains) {
    const body = renderDtsFile(domain);
    const filePath = join(args.outDir, domain.outputFile);
    await fse.outputFile(filePath, body);
    info(
      `wrote ${relative(args.appRoot, filePath)} (${domain.types.length} type${domain.types.length === 1 ? '' : 's'})`,
    );
  }

  // ── schema-map.json ───────────────────────────────────────────
  const map: Record<string, string[]> = {};
  for (const domain of args.domains) {
    map[domain.name] = domain.types.map((t) => t.name);
  }
  const mapPath = join(args.outDir, 'schema-map.json');
  await fse.outputFile(mapPath, JSON.stringify(map, null, 2) + '\n');
  info(`wrote ${relative(args.appRoot, mapPath)}`);

  // ── AI_MANIFEST.md at the app root ────────────────────────────
  const manifestPath = join(args.appRoot, 'AI_MANIFEST.md');
  await fse.outputFile(manifestPath, renderManifest(args));
  info(`wrote ${relative(args.appRoot, manifestPath)}`);
}

/** Render one per-domain `.d.ts` file. The `export type Foo = …`
 *  bodies came from the extractor pre-resolved, so this is little
 *  more than a stable header + a join. */
function renderDtsFile(domain: ExtractedDomain): string {
  const header = [
    HEADER_PREFIX,
    '//',
    `// Domain: ${domain.name} (${domain.origin})`,
    '// Re-run `schema-gen` (or `pnpm ai:context` from the consuming app)',
    '// after schema changes to refresh this file.',
    '',
  ].join('\n');

  if (domain.types.length === 0) {
    return `${header}\n// (no types)\nexport {};\n`;
  }

  const body = domain.types
    .map((t) => `export type ${t.name} = ${t.text};`)
    .join('\n\n');
  return `${header}\n${body}\n`;
}

/** Render the routing-table Markdown manifest. Paths are POSIX-
 *  relative to the app root so the file renders identically on
 *  macOS, Linux, and Windows. */
function renderManifest(args: WriteOutputArgs): string {
  const relOutDir = toPosix(relative(args.appRoot, args.outDir));
  const lines: string[] = [];
  lines.push('# AI Context Manifest');
  lines.push('');
  lines.push(
    '> Auto-generated by `@unsupervised/schemas` / `schema-gen`. Do not edit by hand — re-run `pnpm ai:context` after schema changes.',
  );
  lines.push('');
  lines.push('## Routing rules for AI agents');
  lines.push('');
  lines.push(
    'This file is the **routing table** for any AI agent working in this app. Loading every `.d.ts` at once flushes the LLM context window with data shapes that are irrelevant to the current task. Instead:',
  );
  lines.push('');
  lines.push(
    '1. Identify which domain your task touches (e.g. authoring weapon balance → `weapons`).',
  );
  lines.push(
    '2. Open ONLY the corresponding `.d.ts` file from the table below. Read every type defined there.',
  );
  lines.push(
    '3. Use those types directly. Do NOT redefine them; do NOT paraphrase them; do NOT infer schema shapes from memory.',
  );
  lines.push(
    '4. If your task spans multiple domains, load each manifest entry separately — one at a time. Never bulk-load `' +
      relOutDir +
      '/`.',
  );
  lines.push('');
  lines.push('## Domains');
  lines.push('');
  lines.push('| Domain | Origin | File | Exported types |');
  lines.push('| --- | --- | --- | --- |');
  for (const domain of args.domains) {
    const relFile = `./${posix.join(relOutDir, domain.outputFile)}`;
    const typeList =
      domain.types.length === 0
        ? '_(none)_'
        : domain.types.map((t) => `\`${t.name}\``).join(', ');
    lines.push(
      `| \`${domain.name}\` | ${domain.origin} | [${relFile}](${relFile}) | ${typeList} |`,
    );
  }
  lines.push('');
  lines.push('## Programmatic access');
  lines.push('');
  lines.push(
    `\`${posix.join(relOutDir, 'schema-map.json')}\` is a JSON dump of the same table — useful when an automation needs to pick a domain to load without parsing this Markdown.`,
  );
  lines.push('');
  return lines.join('\n');
}

function toPosix(p: string): string {
  return p.split(sep).join(posix.sep);
}
