// Asset narrative-drift report shapes — the UPSTREAM verify arm for
// the asset-gen (2D image) pipeline, the analog of `audioDrift.ts`.
// Where the review arm judges the generated bytes, this watches the
// SOURCES a prompt was grounded in — the narrative card (SUBJECT) AND
// the Art Bible (STYLE) — and flags images that went stale when
// either changed.
//
// Reuses the generic `DriftStatus` + `DriftCardComparison` from
// `audioDrift.ts` (both are asset-agnostic); adds the Art Bible
// axis, which audio has no analog for.

import { z } from 'zod';
import {
  DriftCardComparisonSchema,
  DriftStatusSchema,
} from './audioDrift.js';

/** The Art Bible (STYLE) fingerprint comparison behind a drift
 *  entry. Present when the sidecar was grounded in a Bible. */
export const BibleComparisonSchema = z.object({
  /** Stored fingerprint (grounding record); null when un-stamped. */
  was: z.string().nullable(),
  /** Current fingerprint; null when the Bible is absent. */
  now: z.string().nullable(),
  changed: z.boolean(),
});
export type BibleComparison = z.infer<typeof BibleComparisonSchema>;

export const AssetDriftEntrySchema = z.object({
  slot: z.string(),
  role: z.enum(['sprite', 'texture', 'ui', 'concept', 'model']),
  status: DriftStatusSchema,
  /** Per-card (SUBJECT) comparisons. */
  cards: z.array(DriftCardComparisonSchema),
  /** Art Bible (STYLE) comparison; null when the image wasn't
   *  grounded in a Bible. */
  bible: BibleComparisonSchema.nullable(),
  groundedAt: z.string().nullable(),
});
export type AssetDriftEntry = z.infer<typeof AssetDriftEntrySchema>;

export const AssetDriftReportSchema = z.object({
  schemaVersion: z.literal(1),
  generatedAt: z.string(),
  entries: z.array(AssetDriftEntrySchema),
  counts: z.object({
    fresh: z.number().int().nonnegative(),
    drifted: z.number().int().nonnegative(),
    groundable: z.number().int().nonnegative(),
    orphaned: z.number().int().nonnegative(),
    ungrounded: z.number().int().nonnegative(),
  }),
});
export type AssetDriftReport = z.infer<typeof AssetDriftReportSchema>;
