// Narrative-drift report shapes — the UPSTREAM verification arm for
// the audio-gen pipeline. Where `audioReview.ts` shapes the
// downstream verdict (generated bytes → judge), this shapes the
// upstream staleness signal (a narrative card changed → the audio
// prompts grounded in it are stale).
//
// The runtime that produces these lives in `@unsupervised/audio-gen` (the
// `drift/` module); this file is the data contract the producer
// (forge / CLI) and consumers (the skill, workbench) share. The
// grounding record it compares against (`AudioGroundingSchema`)
// lives on the sidecar in `audioGen.ts`.

import { z } from 'zod';

/** Per-sidecar drift status. Two directions of staleness:
 *    - `drifted`    — a card this line was GROUNDED in has changed
 *      since (its content fingerprint no longer matches).
 *    - `groundable` — a card this line INFERRED (no card at
 *      grounding time) now exists on disk — re-ground for fidelity.
 *  Plus the terminal / neutral states:
 *    - `fresh`      — every resolved card's fingerprint matches.
 *    - `orphaned`   — a grounded card was deleted / renamed away.
 *    - `ungrounded` — the sidecar has no grounding record (never
 *      run through `narrative-audio-direction`). Informational. */
export const DriftStatusSchema = z.enum([
  'fresh',
  'drifted',
  'groundable',
  'orphaned',
  'ungrounded',
]);
export type DriftStatus = z.infer<typeof DriftStatusSchema>;

/** Per-card comparison detail behind a drift entry. */
export const DriftCardComparisonSchema = z.object({
  cardId: z.string(),
  /** Whether a card was resolved at grounding time. */
  resolved: z.boolean(),
  /** Stored fingerprint (from the grounding record); null when
   *  un-stamped or unresolved. */
  was: z.string().nullable(),
  /** Current fingerprint; null when the card file is absent. */
  now: z.string().nullable(),
  changed: z.boolean(),
});
export type DriftCardComparison = z.infer<typeof DriftCardComparisonSchema>;

/** One sidecar's drift verdict + the per-card detail behind it. */
export const DriftEntrySchema = z.object({
  slot: z.string(),
  kind: z.enum(['voice', 'sfx', 'music']),
  status: DriftStatusSchema,
  cards: z.array(DriftCardComparisonSchema),
  /** Which fields the grounding record marked (what a re-ground
   *  would rewrite). */
  fields: z.array(z.enum(['prompt', 'text'])),
  /** When the sidecar was last grounded; null when ungrounded. */
  groundedAt: z.string().nullable(),
});
export type DriftEntry = z.infer<typeof DriftEntrySchema>;

/** The full report — every discovered sidecar + a status rollup.
 *  Persisted to `<game>/.audio-gen-drift.json`. */
export const DriftReportSchema = z.object({
  schemaVersion: z.literal(1),
  generatedAt: z.string(),
  entries: z.array(DriftEntrySchema),
  /** Count per status, for a quick summary line. Every status is
   *  always present (0 when none) so consumers needn't guard. */
  counts: z.object({
    fresh: z.number().int().nonnegative(),
    drifted: z.number().int().nonnegative(),
    groundable: z.number().int().nonnegative(),
    orphaned: z.number().int().nonnegative(),
    ungrounded: z.number().int().nonnegative(),
  }),
});
export type DriftReport = z.infer<typeof DriftReportSchema>;
