// Weapon config — the shape of a single weapon definition loaded from JSON
// (or generated by a content pipeline, or authored by an LLM given this
// schema as a prompt). The engine instantiates live weapon instances from
// these configs; nothing here encodes runtime state like ammo count.

import { z } from 'zod';

export const WeaponConfigSchema = z.object({
  /** Stable registry key. Used to look the weapon up from inventories,
   *  pickups, and save data. Must be unique across the weapon registry. */
  id: z.string().min(1),

  /** Human-readable display name for UI. */
  name: z.string().min(1),

  /** Damage dealt per successful hit, in HP. */
  damage: z.number().positive(),

  /** Shots per second. Fractional values are valid (0.5 == one shot
   *  every two seconds). The weapon system converts this into a
   *  cooldown at runtime. */
  fireRate: z.number().positive(),

  /** Asset-registry key for the first-person / held model. Resolved by
   *  the renderer, never imported directly. */
  modelId: z.string().min(1),

  /** Asset-registry key for the fire sound. The audio system resolves. */
  audioId: z.string().min(1),
});
export type WeaponConfig = z.infer<typeof WeaponConfigSchema>;
